### ISSUE TITLE
Download is very slow

### ISSUE THREAD

**Issue by CosmicWebServices** [Airhogs777/photron#3]

**Comment by mrjacobbloom** [comment]
How long is the download taking for you? Does it take a long time to start downloading after you've hit the "download" button? What's the size of the file that downloaded?

**Comment by CosmicWebServices** [comment]
It took me about 5 minutes to load before it actually started downloading and it was 300 kb +

That does not include the time to start up the server

**Comment by mrjacobbloom** [comment]
Okay... I've made some changes to the code, would you mind trying again?

**Comment by CosmicWebServices** [comment]
OK!

**Comment by CosmicWebServices** [comment]
That seemed to fix it! Thanks!
