### ISSUE TITLE
App doesn't resize for fullscreen

### ISSUE THREAD

**Issue by mrjacobbloom** [Airhogs777/photron#5]
via https://scratch.mit.edu/discuss/topic/231946/?page=3#post-2374560
> On Ubuntu 16.04, when I go into  full screen, the ui changes and everything gets bigger, but the window size doesn't change and everything goes off the screen.

**Comment by mrjacobbloom** [comment]
Yup, it looks like the full-screen styles were lost somewhere along the way:
<img width="1280" alt="screen shot 2017-01-03 at 3 39 28 pm" src="https://cloud.githubusercontent.com/assets/2879020/21625853/07f820d2-d1cb-11e6-8619-4d4b26ebe4ae.png">
(this is on my Mac)

It sounds like scratchyone was reporting the opposite issue, the UI scales up but it's cropped onto a window-sized square

**Comment by mrjacobbloom** [comment]
MATU set resizable to false: https://github.com/Airhogs777/photron/commit/243416b7fc86c3a600faf5ee294af6f504300ba7#diff-3f210f191e93f71a002213c98c941137R16

@MegaApuTurkUltra what was the reasoning there?

**Comment by MegaApuTurkUltra** [comment]
It works on Windows. It might be phosphorus not picking up the event correctly

**Comment by mrjacobbloom** [comment]
But why'd you disable window resize? I know fullscreen worked on Mac before

**Comment by MegaApuTurkUltra** [comment]
Because resizing the window looked ugly; it created a bunch of white space while the stage stayed the same size. If you make the stage auto-resize with the window, it would be better

**Comment by mrjacobbloom** [comment]
It should resize when it detects that the window size changed... I'll look into it

**Comment by mrjacobbloom** [comment]
fixed that. Now full-screen works correctly for me, and I've asked scratchyone to test it

**Comment by scratchyone** [comment]
It works now, thanks!

**Comment by mrjacobbloom** [comment]
Awesome, then I'll close this.
